# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: arutsevi <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/02/26 15:27:11 by arutsevi          #+#    #+#              #
#    Updated: 2023/02/26 17:15:47 by arutsevi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME    =   rush-02
SRC     =   main.c	check_input.c	dict.c	fill_zeros.c	ft_get_100.c	ft_putchar.c	ft_putnbr.c	ft_putstr.c	ft_remove_extra.c	ft_strcat.c	ft_strcpy.c	ft_strlen.c	ft_strstr.c	ft_strncat.c	my_strtok.c	prepare_string.c	print_res.c	split_num.c			
CFLAGS  =   -Wall -Wextra -Werror

all:    $(NAME)

$(NAME):    
		cc $(CFLAGS) -o $(NAME) $(SRC)
clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)
